# -*- coding: utf-8 -*-
"""CaeserCipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V2Qz-OG6YK-F0bRA9LAocCWhu5c7HzZ
"""

def encrypt(text, shift):
    result = ""
    for char in text:
        if char.isalpha():
            shift_base = ord('A') if char.isupper() else ord('a')
            result += chr((ord(char) - shift_base + shift) % 26 + shift_base)
        else:
            result += char
    return result

def decrypt(text, shift):
    return encrypt(text, -shift)

# Main program
print("=== Caesar Cipher Encryption & Decryption ===")
choice = input("Do you want to (E)ncrypt or (D)ecrypt? ").strip().upper()

message = input("Enter your message: ")
while True:
    try:
        shift = int(input("Enter shift value (e.g., 3): "))
        break
    except ValueError:
        print("Please enter a valid integer for the shift.")

if choice == 'E':
    encrypted = encrypt(message, shift)
    print(f"\nEncrypted message: {encrypted}")
elif choice == 'D':
    decrypted = decrypt(message, shift)
    print(f"\nDecrypted message: {decrypted}")
else:
    print("Invalid option selected.")